# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

#platform :ios do
#  desc "Description of what the lane does"
 # lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
#  end
#end

platform :ios do

  desc "Run unit tests"
  lane :test do
    run_tests(
      scheme: "Automation",
	clean: true,
    code_coverage: true
     # devices: ["iPhone 16"]
    )
  end

  desc "Build app"
  lane :build do
    build_app(
      scheme: "Automation",
	clean: true
    )
  end

end

